server.port=8080


# MySQL Connection URL

spring.datasource.url=jdbc:mysql://localhost:3306/student_db
spring.datasource.username=root
spring.datasource.password=hammad123

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=5A8fD2L9mQ7xP4zR8tV3yN6wK1sE5bH9uC7jF4nL2aQ8mR6pX1zV5yT3kW9sN4dG

jwt.access-expiration=900000
jwt.refresh-expiration=604800000
aes.secret=FORB1fnMXHAYV+DawzyxWExX856OzmJ+zMFtEdSYHuA=
#
#server.port=8080
#
## MySQL Connection URL
#spring.datasource.url=jdbc:mysql://localhost:3306/student_db
#spring.datasource.username=${DB_USERNAME:root}
#spring.datasource.password=${DB_PASSWORD}
#
## MySQL Driver
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## Hibernate Settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#jwt.secret=${JWT_SECRET}
#jwt.access-expiration=900000
#jwt.refresh-expiration=604800000
#
#aes.secret=${AES_SECRET}